package com.example.djfx

object FactoryFxCatalog {
    data class Entry(val id: String, val name: String, val category: String, val url: String)

    val entries = listOf(
        Entry("dj_bell", "Bell", "DJ FX", "https://raw.githubusercontent.com/code4fukui/sound-cc0/main/bell1.wav"),
        Entry("dj_metal", "Metal", "DJ FX", "https://raw.githubusercontent.com/code4fukui/sound-cc0/main/metal1.wav"),
        Entry("dj_steel", "Steel", "DJ FX", "https://raw.githubusercontent.com/code4fukui/sound-cc0/main/steel1.wav"),
        Entry("dj_switch", "Switch", "DJ FX", "https://raw.githubusercontent.com/code4fukui/sound-cc0/main/switch1.wav"),
        Entry("dj_cracker", "Cracker", "DJ FX", "https://raw.githubusercontent.com/code4fukui/sound-cc0/main/cracker1.wav"),
        Entry("dj_cracker_st", "Cracker Stereo", "DJ FX", "https://raw.githubusercontent.com/code4fukui/sound-cc0/main/cracker1v-stereo.wav"),
        Entry("dj_wahaha", "Laugh", "DJ FX", "https://raw.githubusercontent.com/code4fukui/sound-cc0/main/wahaha.wav"),
        Entry("dj_laser", "Laser", "DJ FX", "https://raw.githubusercontent.com/manuel-palacio/brickstorm/main/public/audio/laser.ogg"),
        Entry("dj_break", "Break Hit", "DJ FX", "https://raw.githubusercontent.com/manuel-palacio/brickstorm/main/public/audio/brick-break.ogg"),
        Entry("dj_drop", "Drop", "DJ FX", "https://raw.githubusercontent.com/manuel-palacio/brickstorm/main/public/audio/powerup-drop.ogg"),
        Entry("dj_power", "Power Up", "DJ FX", "https://raw.githubusercontent.com/manuel-palacio/brickstorm/main/public/audio/powerup-get.ogg"),
        Entry("dj_jingle", "Hit Jingle", "DJ FX", "https://raw.githubusercontent.com/manuel-palacio/brickstorm/main/public/audio/life-lost.ogg"),
        Entry("dj_click", "Click", "DJ FX", "https://raw.githubusercontent.com/manuel-palacio/brickstorm/main/public/audio/ui-click.ogg"),
        Entry("dj_move", "Move", "DJ FX", "https://raw.githubusercontent.com/manuel-palacio/brickstorm/main/public/audio/ui-move.ogg"),
        Entry("dj_charge", "Charge", "DJ FX", "https://raw.githubusercontent.com/manuel-palacio/brickstorm/main/public/audio/sfx-charge.ogg"),
        Entry("dj_boom", "Deep Boom", "DJ FX", "https://raw.githubusercontent.com/euuuuuuan/voidclad-public/main/assets/sfx/core_boom.wav"),
        Entry("dr_k1", "Kick 1", "Drums", "https://raw.githubusercontent.com/Boochi44/free-drum-samples/main/drum-samples/01-hard-trap/kicks/hard-kick-01.wav"),
        Entry("dr_k2", "Kick 2", "Drums", "https://raw.githubusercontent.com/Boochi44/free-drum-samples/main/drum-samples/01-hard-trap/kicks/hard-kick-02.wav"),
        Entry("dr_k3", "Kick 3", "Drums", "https://raw.githubusercontent.com/Boochi44/free-drum-samples/main/drum-samples/01-hard-trap/kicks/hard-kick-03.wav"),
        Entry("dr_808d", "808 Dist", "Drums", "https://raw.githubusercontent.com/Boochi44/free-drum-samples/main/drum-samples/01-hard-trap/808s/808-bass-dist.wav"),
        Entry("dr_808s", "808 Sub", "Drums", "https://raw.githubusercontent.com/Boochi44/free-drum-samples/main/drum-samples/01-hard-trap/808s/808-bass-sub.wav"),
        Entry("dr_s1", "Snare 1", "Drums", "https://raw.githubusercontent.com/Boochi44/free-drum-samples/main/drum-samples/01-hard-trap/snares/hard-snare-01.wav"),
        Entry("dr_s2", "Snare 2", "Drums", "https://raw.githubusercontent.com/Boochi44/free-drum-samples/main/drum-samples/01-hard-trap/snares/hard-snare-02.wav"),
        Entry("dr_s3", "Snare 3", "Drums", "https://raw.githubusercontent.com/Boochi44/free-drum-samples/main/drum-samples/01-hard-trap/snares/hard-snare-03.wav"),
        Entry("dr_c1", "Clap 1", "Drums", "https://raw.githubusercontent.com/Boochi44/free-drum-samples/main/drum-samples/01-hard-trap/claps/clap-01.wav"),
        Entry("dr_c2", "Clap 2", "Drums", "https://raw.githubusercontent.com/Boochi44/free-drum-samples/main/drum-samples/01-hard-trap/claps/cl.wav"),
        Entry("dr_h1", "Closed Hat", "Drums", "https://raw.githubusercontent.com/Boochi44/free-drum-samples/main/drum-samples/01-hard-trap/hi-hats/hi-hat-closed-01.wav"),
        Entry("dr_h2", "Closed Hat 2", "Drums", "https://raw.githubusercontent.com/Boochi44/free-drum-samples/main/drum-samples/01-hard-trap/hi-hats/ch.wav"),
        Entry("dr_oh", "Open Hat", "Drums", "https://raw.githubusercontent.com/Boochi44/free-drum-samples/main/drum-samples/01-hard-trap/open-hats/open-hat-01.wav"),
        Entry("dr_cb", "Cowbell", "Drums", "https://raw.githubusercontent.com/Boochi44/free-drum-samples/main/drum-samples/01-hard-trap/percs/perc-cowbell.wav"),
        Entry("dr_rim", "Rimshot", "Drums", "https://raw.githubusercontent.com/Boochi44/free-drum-samples/main/drum-samples/01-hard-trap/percs/perc-rimshot.wav"),
        Entry("dr_cym", "Cymbal", "Drums", "https://raw.githubusercontent.com/Boochi44/free-drum-samples/main/drum-samples/01-hard-trap/fx/fx-cymbal.wav"),
        Entry("el_k1", "Bounce Kick 1", "Electronic", "https://raw.githubusercontent.com/Boochi44/free-drum-samples/main/drum-samples/02-bounce/kicks/bounce-kick-01.wav"),
        Entry("el_k2", "Bounce Kick 2", "Electronic", "https://raw.githubusercontent.com/Boochi44/free-drum-samples/main/drum-samples/02-bounce/kicks/bounce-kick-02.wav"),
        Entry("el_k3", "Bounce Kick 3", "Electronic", "https://raw.githubusercontent.com/Boochi44/free-drum-samples/main/drum-samples/02-bounce/kicks/bounce-kick-03.wav"),
        Entry("el_808l", "808 Long", "Electronic", "https://raw.githubusercontent.com/Boochi44/free-drum-samples/main/drum-samples/02-bounce/808s/808-bass-long.wav"),
        Entry("el_808p", "808 Punch", "Electronic", "https://raw.githubusercontent.com/Boochi44/free-drum-samples/main/drum-samples/02-bounce/808s/808-bass-punch.wav"),
        Entry("el_s1", "Bounce Snare 1", "Electronic", "https://raw.githubusercontent.com/Boochi44/free-drum-samples/main/drum-samples/02-bounce/snares/bounce-snare-01.wav"),
        Entry("el_s2", "Bounce Snare 2", "Electronic", "https://raw.githubusercontent.com/Boochi44/free-drum-samples/main/drum-samples/02-bounce/snares/bounce-snare-02.wav"),
        Entry("el_s3", "Bounce Snare 3", "Electronic", "https://raw.githubusercontent.com/Boochi44/free-drum-samples/main/drum-samples/02-bounce/snares/bounce-snare-03.wav"),
        Entry("el_c1", "Bounce Clap", "Electronic", "https://raw.githubusercontent.com/Boochi44/free-drum-samples/main/drum-samples/02-bounce/claps/clap-01.wav"),
        Entry("el_h1", "Bounce Hat", "Electronic", "https://raw.githubusercontent.com/Boochi44/free-drum-samples/main/drum-samples/02-bounce/hi-hats/hi-hat-closed-01.wav"),
        Entry("el_oh", "Bounce Open Hat", "Electronic", "https://raw.githubusercontent.com/Boochi44/free-drum-samples/main/drum-samples/02-bounce/open-hats/open-hat-01.wav"),
        Entry("el_ht", "High Tom", "Electronic", "https://raw.githubusercontent.com/Boochi44/free-drum-samples/main/drum-samples/02-bounce/percs/perc-high-tom.wav"),
        Entry("el_lt", "Low Tom", "Electronic", "https://raw.githubusercontent.com/Boochi44/free-drum-samples/main/drum-samples/02-bounce/percs/perc-low-tom.wav"),
        Entry("el_808r", "808 Round", "Electronic", "https://raw.githubusercontent.com/Boochi44/free-drum-samples/main/drum-samples/02-bounce/808s/808-round-long.wav"),
        Entry("el_fx", "Bounce FX", "Electronic", "https://raw.githubusercontent.com/Boochi44/free-drum-samples/main/drum-samples/02-bounce/fx/fx-cymbal.wav"),
        Entry("el_laser", "Digital Laser", "Electronic", "https://raw.githubusercontent.com/euuuuuuan/voidclad-public/main/assets/sfx/kenney/laserLarge_001.ogg"),
        Entry("pa_laugh", "Laugh", "Party", "https://raw.githubusercontent.com/code4fukui/sound-cc0/main/wahaha.wav"),
        Entry("pa_bell", "Celebration Bell", "Party", "https://raw.githubusercontent.com/code4fukui/sound-cc0/main/bell1.wav"),
        Entry("pa_crack", "Party Crack", "Party", "https://raw.githubusercontent.com/code4fukui/sound-cc0/main/cracker2.wav"),
        Entry("pa_metal", "Metal Hit", "Party", "https://raw.githubusercontent.com/code4fukui/sound-cc0/main/metal1.wav"),
        Entry("pa_steel", "Steel Hit", "Party", "https://raw.githubusercontent.com/code4fukui/sound-cc0/main/steel1.wav"),
        Entry("pa_x1", "Crunch 1", "Party", "https://raw.githubusercontent.com/euuuuuuan/voidclad-public/main/assets/sfx/kenney/explosionCrunch_002.ogg"),
        Entry("pa_x2", "Crunch 2", "Party", "https://raw.githubusercontent.com/euuuuuuan/voidclad-public/main/assets/sfx/kenney/explosionCrunch_003.ogg"),
        Entry("pa_m1", "Metal Impact", "Party", "https://raw.githubusercontent.com/euuuuuuan/voidclad-public/main/assets/sfx/kenney/impactMetal_light_003.ogg"),
        Entry("pa_m2", "Metal Impact 2", "Party", "https://raw.githubusercontent.com/euuuuuuan/voidclad-public/main/assets/sfx/kenney/impactMetal_medium_002.ogg"),
        Entry("pa_laser", "Laser Party", "Party", "https://raw.githubusercontent.com/manuel-palacio/brickstorm/main/public/audio/laser.ogg"),
        Entry("pa_drop", "Drop", "Party", "https://raw.githubusercontent.com/manuel-palacio/brickstorm/main/public/audio/powerup-drop.ogg"),
        Entry("pa_power", "Power", "Party", "https://raw.githubusercontent.com/manuel-palacio/brickstorm/main/public/audio/powerup-get.ogg"),
        Entry("pa_jingle", "Jingle", "Party", "https://raw.githubusercontent.com/manuel-palacio/brickstorm/main/public/audio/life-lost.ogg"),
        Entry("pa_click", "Click", "Party", "https://raw.githubusercontent.com/manuel-palacio/brickstorm/main/public/audio/ui-click.ogg"),
        Entry("pa_charge", "Charge", "Party", "https://raw.githubusercontent.com/manuel-palacio/brickstorm/main/public/audio/sfx-charge.ogg"),
        Entry("pa_boom", "Deep Boom", "Party", "https://raw.githubusercontent.com/euuuuuuan/voidclad-public/main/assets/sfx/core_boom.wav")
    )
}
